/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "on-secondary-fixed": "#111c2d",
        "on-primary-container": "#0d0096",
        "surface-tint": "#c0c1ff",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary": "#1000a9",
        "secondary-fixed": "#d8e3fb",
        "inverse-on-surface": "#283044",
        "primary": "#c0c1ff",
        "on-secondary-container": "#aeb9d0",
        "outline-variant": "#464554",
        "surface-container-lowest": "#060e20",
        "tertiary-container": "#d97721",
        "on-surface": "#dae2fd",
        "on-secondary": "#263143",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-highest": "#2d3449",
        "surface-dim": "#0b1326",
        "error-container": "#93000a",
        "primary-container": "#8083ff",
        "surface-bright": "#31394d",
        "on-tertiary-fixed-variant": "#703700",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#494bd6",
        "on-error": "#690005",
        "tertiary": "#ffb783",
        "error": "#ffb4ab",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "on-primary-fixed": "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-background": "#dae2fd",
        "surface-container": "#171f33",
        "secondary-container": "#3e495d",
        "surface-container-low": "#131b2e",
        "secondary": "#bcc7de",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary": "#4f2500",
        "background": "#0b1326",
        "outline": "#908fa0",
        "on-tertiary-fixed": "#301400",
        "primary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#ffb783",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-container": "#452000",
        "on-secondary-fixed-variant": "#3c475a",
        "surface": "#0b1326",
        slate: {
          900: '#0f172a',
          800: '#1e293b',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
        },
        indigo: {
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
        }
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
