import json
import boto3
import os
from datetime import datetime, timezone, timedelta

logs_client = boto3.client('logs', region_name='eu-north-1')
sns_client = boto3.client('sns', region_name='eu-north-1')
bedrock_client = boto3.client('bedrock-runtime', region_name='eu-north-1')

SNS_TOPIC_ARN = os.environ['SNS_TOPIC_ARN']

def get_recent_logs(log_group_name, minutes=10):
    end_time = int(datetime.now(timezone.utc).timestamp() * 1000)
    start_time = int((datetime.now(timezone.utc) - timedelta(minutes=minutes)).timestamp() * 1000)
    try:
        response = logs_client.filter_log_events(
            logGroupName=log_group_name,
            startTime=start_time,
            endTime=end_time,
            limit=50
        )
        events = response.get('events', [])
        if not events:
            return "No recent logs found."
        return '\n'.join([e['message'] for e in events])
    except Exception as e:
        return f"Could not fetch logs: {str(e)}"

def analyze_with_bedrock(alarm_name, alarm_reason, logs):
    prompt = f"""You are an expert DevOps engineer and AWS specialist.

A CloudWatch alarm has triggered in a production microservices system running on AWS ECS Fargate.

ALARM NAME: {alarm_name}
ALARM REASON: {alarm_reason}

RECENT APPLICATION LOGS:
{logs}

Please provide:
1. SUMMARY: A 2-3 sentence plain English summary of what went wrong
2. ROOT CAUSE: The most likely root cause based on the logs and alarm
3. IMMEDIATE ACTION: The first thing the engineer should do right now
4. FULL FIX: Step by step instructions to fully resolve this issue
5. PREVENTION: How to prevent this from happening again

Be specific, actionable, and concise."""

    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 1024,
        "messages": [
            {"role": "user", "content": prompt}
        ]
    })

    try:
        response = bedrock_client.invoke_model(
            modelId="anthropic.claude-haiku-4-5",
            contentType="application/json",
            accept="application/json",
            body=body
        )
        result = json.loads(response['body'].read())
        return result['content'][0]['text']
    except Exception as e:
        return f"AI analysis failed: {str(e)}"

def determine_log_group(alarm_name):
    mapping = {
        'auth-service': '/ecs/auth-service',
        'user-service': '/ecs/user-service',
        'api-gateway': '/ecs/api-gateway',
        'alb-5xx': '/ecs/auth-service'
    }
    for key, log_group in mapping.items():
        if key in alarm_name.lower():
            return log_group
    return '/ecs/auth-service'

def lambda_handler(event, context):
    print(f"Event: {json.dumps(event)}")

    detail = event.get('detail', {})
    alarm_name = detail.get('alarmName', 'Unknown Alarm')
    alarm_reason = detail.get('state', {}).get('reason', 'No reason provided')
    new_state = detail.get('state', {}).get('value', 'UNKNOWN')

    if new_state != 'ALARM':
        print(f"State is {new_state} — skipping")
        return {'statusCode': 200, 'body': 'Not ALARM state, skipping'}

    log_group = determine_log_group(alarm_name)
    logs = get_recent_logs(log_group, minutes=10)
    analysis = analyze_with_bedrock(alarm_name, alarm_reason, logs)

    timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')
    subject = f"AIOps Alert: {alarm_name} — {timestamp}"
    body = f"""
=====================================
  AIOPS INCIDENT REPORT — {timestamp}
=====================================

ALARM:  {alarm_name}
REASON: {alarm_reason}

-------------------------------------
  AI ANALYSIS (Claude Haiku on Bedrock)
-------------------------------------

{analysis}

-------------------------------------
  RAW LOGS (Last 10 minutes)
-------------------------------------

{logs[:2000]}

=====================================
  Auto-generated by AIOps Lambda
  Cluster: microservices-cluster | Region: eu-north-1
=====================================
"""

    sns_client.publish(
        TopicArn=SNS_TOPIC_ARN,
        Subject=subject,
        Message=body
    )

    print("AIOps report sent")
    return {'statusCode': 200, 'body': 'Report sent successfully'}