server:
  port: 8082

spring:
  application:
    name: user-service

jwt:
  secret: ${JWT_SECRET:defaultsecret}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-origins-1: ${CORS_ALLOWED_ORIGINS_1:http://localhost:3000}
  allowed-origins-2: ${CORS_ALLOWED_ORIGINS_2:https://app.cybrmoon.space}

logging:
  level:
    root: INFO
    com.userservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
